In [4]:
import tensorflow as tf
import numpy as np

In [6]:
tf.__version__

'2.4.0'

In [7]:
xConstant = tf.constant([[23,4],[33,5]])
xConstant

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [33,  5]])>

In [8]:
xConstant.shape

TensorShape([2, 2])

In [12]:
xConstant.dtype

tf.int32

In [11]:
xConstant.numpy()

array([[23,  4],
       [33,  5]])

In [13]:
np_array = np.array([[22,3],[44,32]])


In [14]:
tensor_array = tf.constant(np_array)

In [17]:
tensor_array.numpy()

array([[22,  3],
       [44, 32]])

In [19]:
tf_variable = tf.Variable([[23,556],[98,9]])

In [21]:
tf_variable.numpy()

array([[ 23, 556],
       [ 98,   9]])

In [24]:
tf_variable[0,1].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[ 23, 100],
       [ 98,   9]])>

In [26]:
tensor = tf.constant([[2,3],[5,5]])

In [27]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [7, 7]])>

In [29]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [50, 50]])>

In [30]:
np.square(tensor)

array([[ 4,  9],
       [25, 25]], dtype=int32)

In [31]:
np.sqrt(tensor)

array([[1.41421356, 1.73205081],
       [2.23606798, 2.23606798]])

In [38]:
np.dot(tensor,tensor)

array([[19, 21],
       [35, 40]])

In [39]:
tf_string = tf.constant("This is Tensorflow")

In [42]:
tf.strings.length(tf_string).numpy()

18

In [43]:
tf.strings.unicode_decode(tf_string,"UTF8")

<tf.Tensor: shape=(18,), dtype=int32, numpy=
array([ 84, 104, 105, 115,  32, 105, 115,  32,  84, 101, 110, 115, 111,
       114, 102, 108, 111, 119])>

In [46]:
tf_string_array = tf.constant(["This","is","Tensorflow"])

In [51]:
for string in tf_string_array:
    print(string)

tf.Tensor(b'This', shape=(), dtype=string)
tf.Tensor(b'is', shape=(), dtype=string)
tf.Tensor(b'Tensorflow', shape=(), dtype=string)
